# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import graph_service_pb2 as graph__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in graph_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitGraph = channel.unary_unary(
                '/graph.GraphService/SubmitGraph',
                request_serializer=graph__service__pb2.GraphSubmission.SerializeToString,
                response_deserializer=graph__service__pb2.SubmissionResponse.FromString,
                _registered_method=True)
        self.HasIndependentSet = channel.unary_unary(
                '/graph.GraphService/HasIndependentSet',
                request_serializer=graph__service__pb2.IndependentSetQuery.SerializeToString,
                response_deserializer=graph__service__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.HasMatching = channel.unary_unary(
                '/graph.GraphService/HasMatching',
                request_serializer=graph__service__pb2.MatchingQuery.SerializeToString,
                response_deserializer=graph__service__pb2.BooleanResponse.FromString,
                _registered_method=True)
        self.GetGraphStatus = channel.unary_unary(
                '/graph.GraphService/GetGraphStatus',
                request_serializer=graph__service__pb2.Empty.SerializeToString,
                response_deserializer=graph__service__pb2.GraphStatus.FromString,
                _registered_method=True)
        self.ResetGraph = channel.unary_unary(
                '/graph.GraphService/ResetGraph',
                request_serializer=graph__service__pb2.ResetRequest.SerializeToString,
                response_deserializer=graph__service__pb2.StatusResponse.FromString,
                _registered_method=True)


class GraphServiceServicer(object):
    """Service definition
    """

    def SubmitGraph(self, request, context):
        """Submit a graph from a client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasIndependentSet(self, request, context):
        """Query for independent set
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HasMatching(self, request, context):
        """Query for matching
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraphStatus(self, request, context):
        """Get current graph status (optional utility method)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetGraph(self, request, context):
        """Add this method for clearing the graph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGraph,
                    request_deserializer=graph__service__pb2.GraphSubmission.FromString,
                    response_serializer=graph__service__pb2.SubmissionResponse.SerializeToString,
            ),
            'HasIndependentSet': grpc.unary_unary_rpc_method_handler(
                    servicer.HasIndependentSet,
                    request_deserializer=graph__service__pb2.IndependentSetQuery.FromString,
                    response_serializer=graph__service__pb2.BooleanResponse.SerializeToString,
            ),
            'HasMatching': grpc.unary_unary_rpc_method_handler(
                    servicer.HasMatching,
                    request_deserializer=graph__service__pb2.MatchingQuery.FromString,
                    response_serializer=graph__service__pb2.BooleanResponse.SerializeToString,
            ),
            'GetGraphStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraphStatus,
                    request_deserializer=graph__service__pb2.Empty.FromString,
                    response_serializer=graph__service__pb2.GraphStatus.SerializeToString,
            ),
            'ResetGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetGraph,
                    request_deserializer=graph__service__pb2.ResetRequest.FromString,
                    response_serializer=graph__service__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'graph.GraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('graph.GraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphService(object):
    """Service definition
    """

    @staticmethod
    def SubmitGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.GraphService/SubmitGraph',
            graph__service__pb2.GraphSubmission.SerializeToString,
            graph__service__pb2.SubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasIndependentSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.GraphService/HasIndependentSet',
            graph__service__pb2.IndependentSetQuery.SerializeToString,
            graph__service__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HasMatching(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.GraphService/HasMatching',
            graph__service__pb2.MatchingQuery.SerializeToString,
            graph__service__pb2.BooleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraphStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.GraphService/GetGraphStatus',
            graph__service__pb2.Empty.SerializeToString,
            graph__service__pb2.GraphStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/graph.GraphService/ResetGraph',
            graph__service__pb2.ResetRequest.SerializeToString,
            graph__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
